namespace EnvironmentHider.Environments.BuiltIn;

public class HalloweenEnvironment : Environment
{
    public HalloweenEnvironment()
    {
        this.Static = new List<EnvironmentObject>
        {
            new("PlayersPlace"),
            new("Ground"),
            new("Grave0"),
            new("Grave0 (1)"),
            new("Grave1"),
            new("Fence"),
            new("Grave"),
            new("Fence (1)"),
            new("Castle"),
            new("Castle (1)"),
            new("Castle (2)"),
            new("Castle (3)"),
            new("Tree3"),
            new("Tree3 (1)"),
            new("Tree3 (2)"),
            new("Tree3 (3)"),
            new("Tree2 (3)"),
            new("Tree2 (2)"),
            new("Tree2"),
            new("Fence (2)"),
            new("Fence (3)"),
            new("Fence"),
            new("Tree5"),
            new("TombStone (2)"),
            new("TombStone (3)"),
            new("TombStone (4)"),
            new("TombStone (5)"),
            new("TombStone (6)"),
            new("TombStone (7)"),
            new("TombStone (8)"),
            new("TombStone (9)"),
            new("TombStone (11)"),
            new("TombStone (12)"),
            new("TombStone (13)"),
            new("TombStone (14)"),
            new("TombStone (15)"),
            new("TombStone (16)"),
            new("TombStone (17)"),
            new("TombStone (18)"),
            new("TombStone (19)"),
            new("TombStone (20)"),
            new("TombStone (21)"),
            new("TombStone (22)"),
            new("TombStone (24)"),
            new("Fence (4)"),
            new("Fence (5)"),
            new("Fence (6)"),
            new("Fence (7)"),
            new("Fence (8)"),
            new("Fence (9)"),
            new("Fence (10)"),
            new("Fence (11)"),
            new("Fence (12)"),
            new("Fence (13)"),
            new("Fence (14)"),
            new("Fence (15)"),
            new("Fence (16)"),
            new("Fence (17)"),
            new("Fence (18)"),
            new("Fence (19)"),
            new("Fence (20)"),
            new("Fence (21)"),
            new("Fence (22)"),
            new("Fence (23)"),
            new("Grave0 (2)"),
            new("Grave1 (1)"),
            new("Grave"),
            new("Fence (24)"),
            new("GroundStone (1)"),
            new("GroundStone (2)"),
            new("GroundStone (3)"),
            new("GroundStone (5)"),
            new("GroundStone (6)"),
            new("GroundStone (7)"),
            new("GroundStone (8)"),
            new("GroundStone (9)"),
            new("GroundStone (10)"),
            new("GroundStone (11)"),
            new("GroundStone (12)"),
            new("GroundStone (13)"),
            new("GroundStone (14)"),
            new("GroundStone (15)"),
            new("GroundStone (16)"),
            new("GroundStone (17)"),
            new("GroundStone (18)"),
            new("GroundStone (19)"),
            new("GroundStone (20)"),
            new("GroundStone (21)"),
            new("GroundStone (22)"),
            new("GroundStone (23)"),
            new("GroundStone (24)"),
            new("GroundStone (25)"),
            new("GroundStone (26)"),
            new("GroundStone (27)"),
            new("GroundStone (28)"),
            new("GroundStone (29)"),
            new("GroundStone (30)"),
            new("GroundStone (31)"),
            new("GroundStone (32)"),
            new("GroundStone (33)"),
            new("GroundStone (34)"),
            new("GroundStone (35)"),
            new("GroundStone (36)"),
            new("GroundStone (38)"),
            new("GroundStone (37)"),
            new("GroundStone (39)"),
            new("GroundStone (4)"),
            new("GroundStone (40)"),
            new("GroundStone (41)"),
            new("GroundStone (42)"),
            new("GroundStone (43)"),
            new("GroundStone (44)"),
            new("GroundStone (45)"),
            new("GroundStone (46)"),
            new("GroundStone (47)"),
            new("GroundStone (48)"),
            new("GroundStone (49)"),
            new("GroundStone (50)"),
            new("GroundStone (51)"),
            new("GroundStone (54)"),
            new("GroundStone (55)"),
            new("GroundStone (56)"),
            new("GroundStone (57)"),
            new("GroundStone (58)"),
            new("GroundStone (59)"),
            new("GroundStone (60)"),
            new("GroundStone (61)"),
            new("GroundStone (62)"),
            new("GroundStone (63)"),
            new("GroundStone (64)"),
            new("GroundStone (65)"),
            new("GroundStone (66)"),
            new("GroundStone (67)"),
            new("GroundStone (68)"),
            new("GroundStone (69)"),
            new("GroundStone (70)"),
            new("GroundStone (71)"),
            new("GroundStone (72)"),
            new("GroundStone (73)"),
            new("GroundStone (74)"),
            new("GroundStone (77)"),
            new("Tree1 (1)"),
            new("Tree2 (1)"),
        };

        this.Dynamic = new List<EnvironmentObject>
        {
            new("Bats"),
            new("NarrowGameHUD"),
            new("BigSmokePS"),
            new("Crow (3)"),
            new("Crow (2)"),
            new("Crow"),
            new("Crow (1)"),
            new("ZombieHand (1)"),
            new("ZombieHand (2)"),
            new("ZombieHand (3)"),
            new("ZombieHand (4)"),
            new("ZombieHand (5)"),
            new("ZombieHand"),
            new("ZombieHand (6)"),
        };

        this.Lights = new List<EnvironmentObject>
        {
            new("CoreLighting"),
            new("NeonTubeL (1)"),
            new("LightEffects"),
            new("LightWithIdManager"),
            new("NeonTubeR"),
            new("NeonTubeL"),
            new("NeonTubeR (1)"),
            new("GateLight"),
            new("Moon"),
            new("GlowLineL (7)"),
            new("GlowLineL (6)"),
            new("GlowLineL (8)"),
            new("GlowLineL (9)"),
            new("NeonTubeC"),
            new("GroundFog"),
            new("RotatingLasersPair (13)"),
            new("RotatingLasersPair (12)"),
            new("RotatingLasersPair (7)"),
            new("RotatingLasersPair (8)"),
            new("RotatingLasersPair (9)"),
            new("RotatingLasersPair (10)"),
            new("RotatingLasersPair (11)"),
            new("RotatingLasersPair (14)"),
            new("RotatingLasersPair (15)"),
            new("RotatingLasersPair (16)"),
            new("RotatingLasersPair (17)"),
            new("RotatingLasersPair (18)"),
            new("RotatingLasersPair (19)"),
            new("RotatingLasersPair (20)"),
            new("RotatingLasersPair (21)"),
            new("RotatingLasersPair (22)"),
            new("RotatingLasersPair (23)"),
            new("GroundStone (52)"),
            new("GroundStone (53)"),
            new("GroundStone (75)"),
            new("GroundStone (76)"),
            new("GroundStone (78)"),
            new("GroundStone (79)"),
            new("GroundStone (80)"),
            new("GroundStone (81)"),
            new("GroundStone (82)"),
            new("GroundStone (83)"),
            new("GroundStone (84)"),
            new("GroundStone (85)"),
            new("GroundStone (86)"),
            new("GroundStone (87)"),
            new("GroundStone (88)"),
            new("GroundStone (89)"),
            new("GroundStone (90)"),
            new("GroundStone (91)"),
        };
    }
}