namespace EnvironmentHider.Environments.BuiltIn;

public class KDAEnvironment : Environment
{
    public KDAEnvironment()
    {
        this.Static = new List<EnvironmentObject>
        {
            new("TentacleLeft"),
            new("TentacleRight"),
            new("Construction"),
            new("FloorMirror"),
            new("PlayersPlace"),
        };

        this.Dynamic = new List<EnvironmentObject>
        {
            new("BasicGameHUD"),
            new("BigSmokePS"),
            new("DustPS"),
        };

        this.Lights = new List<EnvironmentObject>
        {
            new("LightWithIdManager"),
            new("LightEffects"),
            new("CoreLighting"),
            new("FrontLights"),
            new("GlowLineLVisible"),
            new("GlowLineRVisible"),
            new("GlowTopLine"),
            new("GlowTopLine (1)"),
            new("GlowTopLine (2)"),
            new("GlowTopLine (3)"),
            new("GlowTopLine (4)"),
            new("GlowLineFarL"),
            new("GlowLineFarR"),
            new("Laser (2)"),
            new("Laser (3)"),
            new("Laser (4)"),
            new("Laser (7)"),
            new("Laser (8)"),
            new("Laser (9)"),
            new("GlowLine (2)"),
            new("GlowLine (34)"),
            new("GlowLine (36)"),
            new("GlowLine (48)"),
            new("GlowLine (68)"),
            new("GlowLine (27)"),
            new("GlowLine (53)"),
            new("GlowLine (62)"),
            new("GlowLine (65)"),
            new("GlowLine (71)"),
            new("GlowLine (72)"),
            new("GlowLine (42)"),
            new("GlowLine (51)"),
            new("GlowLine (8)"),
            new("GlowLine (24)"),
            new("GlowLine (10)"),
            new("GlowLine (60)"),
            new("GlowLine (76)"),
            new("GlowLine (50)"),
            new("GlowLine (21)"),
            new("GlowLine (58)"),
            new("GlowLine (66)"),
            new("GlowLine (9)"),
            new("GlowLine (7)"),
            new("GlowLine (29)"),
            new("GlowLine (5)"),
            new("GlowLine (44)"),
            new("GlowLine (33)"),
            new("GlowLine (55)"),
            new("GlowLine (16)"),
            new("GlowLine (3)"),
            new("GlowLine (47)"),
            new("GlowLine (35)"),
            new("GlowLine (46)"),
            new("GlowLine (59)"),
            new("GlowLine (64)"),
            new("GlowLine (39)"),
            new("GlowLine (73)"),
            new("GlowLine (54)"),
            new("GlowLine (25)"),
            new("GlowLine (15)"),
            new("GlowLine (14)"),
            new("GlowLine (23)"),
            new("GlowLine (49)"),
            new("GlowLine (19)"),
            new("GlowLine (63)"),
            new("GlowLine (41)"),
            new("GlowLine (67)"),
            new("GlowLine (37)"),
            new("GlowLine (17)"),
            new("GlowLine (69)"),
            new("GlowLine (11)"),
            new("GlowLine (52)"),
            new("GlowLine (6)"),
            new("GlowLine (45)"),
            new("GlowLine (22)"),
            new("GlowLine (28)"),
            new("GlowLine (43)"),
            new("GlowLine (74)"),
            new("GlowLine (4)"),
            new("GlowLine (31)"),
            new("GlowLine (18)"),
            new("GlowLine (1)"),
            new("GlowLine (40)"),
            new("GlowLine (12)"),
            new("GlowLine (70)"),
            new("GlowLine (13)"),
            new("GlowLine (61)"),
            new("GlowLine (75)"),
            new("GlowLine (32)"),
            new("GlowLine (30)"),
            new("GlowLine (57)"),
            new("GlowLine (38)"),
            new("GlowLine (20)"),
            new("GlowLine"),
            new("GlowLine (56)"),
            new("RotatingLasersPair"),
            new("RotatingLasersPair (1)"),
            new("RotatingLasersPair (2)"),
            new("RotatingLasersPair (3)"),
            new("RotatingLasersPair (4)"),
            new("RotatingLasersPair (5)"),
            new("RotatingLasersPair (6)"),
            new("BakedReflectionProbe"),
            new("BSBakedLightingLightWithIds"),
            new("FakeMirrorSettings"),
            new("BakedReflectionProbeInstaller"),
        };
    }
}